language: php

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update

install: composer update --no-interaction --prefer-dist

script: vendor/bin/phpunit
