language: php

cache:
  directories:
    - $COMPOSER_CACHE_DIR

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
